-- mgc.category definition

CREATE TABLE `category` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `STATUS` int NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(20) DEFAULT 'system',
  `UPDATED_BY` varchar(20) DEFAULT 'system',
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `NAME` varchar(80) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;


-- mgc.client definition

CREATE TABLE `client` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `STATUS` int NOT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FIRST_NAME` varchar(80) NOT NULL,
  `ADDRESS` varchar(255) DEFAULT NULL,
  `PHONE_NUMBER` varchar(255) DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=48 DEFAULT CHARSET=latin1;


-- mgc.consumption definition

CREATE TABLE `consumption` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `STATUS` int NOT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FILE_IMPORT_ID` bigint DEFAULT NULL,
  `CORRECTED_VOLUME` decimal(19,4) NOT NULL,
  `CLIENT_ID` bigint DEFAULT NULL,
  `consumption_date` datetime DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=3838 DEFAULT CHARSET=latin1;


-- mgc.corrector definition

CREATE TABLE `corrector` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `STATUS` int NOT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `NAME` varchar(80) NOT NULL,
  `MODEL` varchar(255) DEFAULT NULL,
  `SERIAL_NUMBER` varchar(100) DEFAULT NULL,
  `DOWNLOAD_EXTENSION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=latin1;


-- mgc.file_import definition

CREATE TABLE `file_import` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `STATUS` int NOT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `FILE_NAME` varchar(255) DEFAULT NULL,
  `FILE_DATE` datetime DEFAULT NULL,
  `IMPORT_DATE` datetime DEFAULT NULL,
  `CLIENT_ID` bigint DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=46 DEFAULT CHARSET=latin1;


-- mgc.flyway_schema_history definition

CREATE TABLE `flyway_schema_history` (
  `installed_rank` int NOT NULL,
  `version` varchar(50) DEFAULT NULL,
  `description` varchar(200) NOT NULL,
  `type` varchar(20) NOT NULL,
  `script` varchar(1000) NOT NULL,
  `checksum` int DEFAULT NULL,
  `installed_by` varchar(100) NOT NULL,
  `installed_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `execution_time` int NOT NULL,
  `success` tinyint(1) NOT NULL,
  PRIMARY KEY (`installed_rank`),
  KEY `flyway_schema_history_s_idx` (`success`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- mgc.permission definition

CREATE TABLE `permission` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `STATUS` int NOT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- mgc.product definition

CREATE TABLE `product` (
  `ID` bigint NOT NULL,
  `STATUS` int NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(20) DEFAULT 'system',
  `UPDATED_BY` varchar(20) DEFAULT 'system',
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `NAME` varchar(80) NOT NULL,
  `DESCRIPTION` varchar(255) NOT NULL,
  `UNIT_PRICE` decimal(10,2) NOT NULL,
  `CATEGORY_ID` bigint NOT NULL,
  `REFERENCE` varchar(255) NOT NULL,
  `IMAGE` longtext
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- mgc.product_unit_conversion definition

CREATE TABLE `product_unit_conversion` (
  `ID` bigint NOT NULL,
  `STATUS` int NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(20) DEFAULT 'system',
  `UPDATED_BY` varchar(20) DEFAULT 'system',
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `PRODUCT_ID` bigint NOT NULL,
  `UNIT_ID` bigint NOT NULL,
  `CONVERSION_FACTOR` int NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- mgc.sale definition

CREATE TABLE `sale` (
  `ID` bigint NOT NULL,
  `STATUS` int NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(20) DEFAULT 'system',
  `UPDATED_BY` varchar(20) DEFAULT 'system',
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `CLIENT_ID` bigint DEFAULT NULL,
  `SALE_STATUS` varchar(20) NOT NULL,
  `TOTAL_VALUE` decimal(10,2) NOT NULL,
  KEY `FK_CLIENT_SALE` (`CLIENT_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- mgc.sale_item definition

CREATE TABLE `sale_item` (
  `ID` bigint NOT NULL,
  `STATUS` int NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(20) DEFAULT 'system',
  `UPDATED_BY` varchar(20) DEFAULT 'system',
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `SALE_ID` bigint NOT NULL,
  `PRODUCT_ID` bigint NOT NULL,
  `QUANTITY` int NOT NULL DEFAULT '0',
  `PRODUCT_UNIT_CONVERSION_ID` bigint NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- mgc.stock definition

CREATE TABLE `stock` (
  `ID` bigint NOT NULL,
  `STATUS` int NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(20) DEFAULT 'system',
  `UPDATED_BY` varchar(20) DEFAULT 'system',
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `PRODUCT_ID` bigint NOT NULL,
  `QUANTITY` int NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- mgc.stock_movement definition

CREATE TABLE `stock_movement` (
  `ID` bigint NOT NULL,
  `STATUS` int NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(20) DEFAULT 'system',
  `UPDATED_BY` varchar(20) DEFAULT 'system',
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `STOCK_ID` bigint NOT NULL,
  `MOVEMENT_TYPE` enum('ENTRY','EXIT') NOT NULL,
  `QUANTITY` int NOT NULL,
  `UNIT_SYMBOL` varchar(10) DEFAULT 'UN',
  `OBSERVATION` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- mgc.unit definition

CREATE TABLE `unit` (
  `ID` bigint NOT NULL,
  `STATUS` int NOT NULL DEFAULT '1',
  `CREATED_BY` varchar(20) DEFAULT 'system',
  `UPDATED_BY` varchar(20) DEFAULT 'system',
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `NAME` varchar(100) NOT NULL,
  `SYMBOL` varchar(10) NOT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- mgc.user_permission definition

CREATE TABLE `user_permission` (
  `ID_USER` bigint NOT NULL,
  `STATUS` int NOT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ID_PERMISSION` bigint NOT NULL,
  PRIMARY KEY (`ID_USER`,`ID_PERMISSION`),
  KEY `FK_USER_PERMISSION_PERMISSION` (`ID_PERMISSION`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


-- mgc.users definition

CREATE TABLE `users` (
  `ID` bigint NOT NULL AUTO_INCREMENT,
  `STATUS` int NOT NULL,
  `CREATED_BY` varchar(20) DEFAULT NULL,
  `UPDATED_BY` varchar(20) DEFAULT NULL,
  `CREATED_DATE` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USER_NAME` varchar(255) DEFAULT NULL,
  `FULL_NAME` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `ACCOUNT_NON_EXPIRED` bit(1) DEFAULT NULL,
  `ACCOUNT_NON_LOCKED` bit(1) DEFAULT NULL,
  `CREDENTIALS_NON_EXPIRED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  `IMAGE` longtext,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_USER_NAME` (`USER_NAME`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=latin1;



INSERT INTO mgc.category
(ID, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, NAME, DESCRIPTION)
VALUES(0, 1, 'system', 'system', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '', '');
INSERT INTO mgc.client
(ID, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, FIRST_NAME, ADDRESS, PHONE_NUMBER, EMAIL, `TYPE`)
VALUES(0, 0, '', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '', '', '', '', '');
INSERT INTO mgc.consumption
(ID, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, FILE_IMPORT_ID, CORRECTED_VOLUME, CLIENT_ID, consumption_date)
VALUES(0, 0, '', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0, 0, '');
INSERT INTO mgc.corrector
(ID, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, NAME, MODEL, SERIAL_NUMBER, DOWNLOAD_EXTENSION)
VALUES(0, 0, '', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '', '', '', '');
INSERT INTO mgc.file_import
(ID, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, FILE_NAME, FILE_DATE, IMPORT_DATE, CLIENT_ID)
VALUES(0, 0, '', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '', '', '', 0);
INSERT INTO mgc.flyway_schema_history
(installed_rank, version, description, `type`, script, checksum, installed_by, installed_on, execution_time, success)
VALUES(0, '', '', '', '', 0, '', CURRENT_TIMESTAMP, 0, 0);
INSERT INTO mgc.permission
(ID, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, DESCRIPTION)
VALUES(0, 0, '', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '');
INSERT INTO mgc.product
(ID, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, NAME, DESCRIPTION, UNIT_PRICE, CATEGORY_ID, REFERENCE, IMAGE)
VALUES(0, 1, 'system', 'system', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '', '', 0, 0, '', '');
INSERT INTO mgc.product_unit_conversion
(ID, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, PRODUCT_ID, UNIT_ID, CONVERSION_FACTOR)
VALUES(0, 1, 'system', 'system', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0, 0);
INSERT INTO mgc.sale
(ID, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, CLIENT_ID, SALE_STATUS, TOTAL_VALUE)
VALUES(0, 1, 'system', 'system', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '', 0);
INSERT INTO mgc.sale_item
(ID, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, SALE_ID, PRODUCT_ID, QUANTITY, PRODUCT_UNIT_CONVERSION_ID)
VALUES(0, 1, 'system', 'system', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0, 0, 0);
INSERT INTO mgc.stock
(ID, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, PRODUCT_ID, QUANTITY)
VALUES(0, 1, 'system', 'system', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, 0);
INSERT INTO mgc.stock_movement
(ID, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, STOCK_ID, MOVEMENT_TYPE, QUANTITY, UNIT_SYMBOL, OBSERVATION)
VALUES(0, 1, 'system', 'system', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0, '', 0, 'UN', '');
INSERT INTO mgc.unit
(ID, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, NAME, SYMBOL, DESCRIPTION)
VALUES(0, 1, 'system', 'system', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '', '', '');
INSERT INTO mgc.user_permission
(ID_USER, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, ID_PERMISSION)
VALUES(0, 0, '', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0);
INSERT INTO mgc.users
(ID, STATUS, CREATED_BY, UPDATED_BY, CREATED_DATE, UPDATED_DATE, USER_NAME, FULL_NAME, PASSWORD, ACCOUNT_NON_EXPIRED, ACCOUNT_NON_LOCKED, CREDENTIALS_NON_EXPIRED, ENABLED, IMAGE)
VALUES(0, 0, '', '', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, '', '', '', 0, 0, 0, 0, '');




