CREATE TABLE IF NOT EXISTS `CLIENT` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL,
    `CREATED_BY` VARCHAR(20),
    `UPDATED_BY` VARCHAR(20),
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `FIRST_NAME` VARCHAR(80) NOT NULL,
    `LAST_NAME` VARCHAR(80) NOT NULL,
    `ADDRESS` VARCHAR(100) NOT NULL,
    `PHONE_NUMBER` VARCHAR(15) NOT NULL,
    `EMAIL` VARCHAR(100),
    `TYPE` VARCHAR(20) NOT NULL,
    PRIMARY KEY (`ID`)
);

CREATE TABLE IF NOT EXISTS `PERMISSION` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `STATUS` INT NOT NULL,
  `CREATED_BY` VARCHAR(20),
  `UPDATED_BY` VARCHAR(20),
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `USERS` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `STATUS` INT NOT NULL,
  `CREATED_BY` VARCHAR(20),
  `UPDATED_BY` VARCHAR(20),
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `USER_NAME` varchar(255) DEFAULT NULL,
  `FULL_NAME` varchar(255) DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `ACCOUNT_NON_EXPIRED` bit(1) DEFAULT NULL,
  `ACCOUNT_NON_LOCKED` bit(1) DEFAULT NULL,
  `CREDENTIALS_NON_EXPIRED` bit(1) DEFAULT NULL,
  `ENABLED` bit(1) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `UK_USER_NAME` (`USER_NAME`)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `USER_PERMISSION` (
  `ID_USER` bigint(20) NOT NULL,
  `STATUS` INT NOT NULL,
  `CREATED_BY` VARCHAR(20),
  `UPDATED_BY` VARCHAR(20),
  `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `ID_PERMISSION` bigint(20) NOT NULL,
  PRIMARY KEY (`ID_USER`,`ID_PERMISSION`),
  KEY `FK_USER_PERMISSION_PERMISSION` (`ID_PERMISSION`),
  CONSTRAINT `FK_USER_PERMISSION` FOREIGN KEY (`ID_USER`) REFERENCES `USERS` (`ID`),
  CONSTRAINT `FK_USER_PERMISSION_PERMISSION` FOREIGN KEY (`ID_PERMISSION`) REFERENCES `PERMISSION` (`ID`)
) ENGINE=InnoDB;

