-- ============================================
-- 1. Tabela UNIT
-- ============================================
CREATE TABLE `UNIT` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) DEFAULT 'system',
    `UPDATED_BY` VARCHAR(20) DEFAULT 'system',
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `NAME` VARCHAR(100) NOT NULL,
    `SYMBOL` VARCHAR(10) NOT NULL,
    `DESCRIPTION` VARCHAR(255),
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_UNIT_SYMBOL` (`SYMBOL`)
) ENGINE = InnoDB;

-- ============================================
-- 2. Tabela CATEGORY
-- ============================================
CREATE TABLE `CATEGORY` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) DEFAULT 'system',
    `UPDATED_BY` VARCHAR(20) DEFAULT 'system',
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `NAME` VARCHAR(80) NOT NULL,
    `DESCRIPTION` VARCHAR(255),
    PRIMARY KEY (`ID`)
) ENGINE = InnoDB;

-- ============================================
-- 3. Tabela PRODUCT
-- ============================================
CREATE TABLE `PRODUCT` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) DEFAULT 'system',
    `UPDATED_BY` VARCHAR(20) DEFAULT 'system',
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `NAME` VARCHAR(80) NOT NULL,
    `DESCRIPTION` VARCHAR(255) NOT NULL,
    `UNIT_PRICE` DECIMAL(10,2) NOT NULL,
    `CATEGORY_ID` BIGINT NOT NULL,
    `BASE_UNIT_ID` BIGINT NOT NULL,
    `REFERENCE` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_PRODUCT_CATEGORY` FOREIGN KEY (`CATEGORY_ID`) REFERENCES `CATEGORY`(`ID`),
    CONSTRAINT `FK_PRODUCT_UNIT` FOREIGN KEY (`BASE_UNIT_ID`) REFERENCES `UNIT`(`ID`)
) ENGINE = InnoDB;

-- ============================================
-- 4. Tabela PRODUCT_UNIT_CONVERSION
-- ============================================
CREATE TABLE `PRODUCT_UNIT_CONVERSION` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) DEFAULT 'system',
    `UPDATED_BY` VARCHAR(20) DEFAULT 'system',
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `PRODUCT_ID` BIGINT NOT NULL,
    `UNIT_ID` BIGINT NOT NULL,
    `CONVERSION_FACTOR` INT NOT NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_PUC_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`ID`) ON DELETE CASCADE,
    CONSTRAINT `FK_PUC_UNIT` FOREIGN KEY (`UNIT_ID`) REFERENCES `UNIT`(`ID`)
) ENGINE = InnoDB;

-- ============================================
-- 5. Tabela STOCK
-- ============================================
CREATE TABLE `STOCK` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) DEFAULT 'system',
    `UPDATED_BY` VARCHAR(20) DEFAULT 'system',
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `PRODUCT_ID` BIGINT NOT NULL,
    `QUANTITY` INT NOT NULL DEFAULT 0,
    PRIMARY KEY (`ID`),
    UNIQUE KEY `UK_STOCK_PRODUCT` (`PRODUCT_ID`),
    CONSTRAINT `FK_STOCK_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`ID`) ON DELETE CASCADE
) ENGINE = InnoDB;

-- ============================================
-- 6. Tabela STOCK_MOVEMENT
-- ============================================
CREATE TABLE `STOCK_MOVEMENT` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) DEFAULT 'system',
    `UPDATED_BY` VARCHAR(20) DEFAULT 'system',
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `STOCK_ID` BIGINT NOT NULL,
    `MOVEMENT_TYPE` ENUM('ENTRY','EXIT') NOT NULL,
    `QUANTITY` INT NOT NULL,
    `UNIT_SYMBOL` VARCHAR(10) DEFAULT 'UN',
    `OBSERVATION` VARCHAR(255),
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_MOVEMENT_PRODUCT` FOREIGN KEY (`STOCK_ID`) REFERENCES `STOCK`(`ID`) ON DELETE CASCADE
) ENGINE = InnoDB;


CREATE TABLE `SALE` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) DEFAULT 'system',
    `UPDATED_BY` VARCHAR(20) DEFAULT 'system',
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `CLIENT_ID` BIGINT ,
    `SALE_STATUS` VARCHAR(20) NOT NULL,
    `TOTAL_VALUE` DECIMAL(10,2) NOT NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_CLIENT_SALE` FOREIGN KEY (`CLIENT_ID`) REFERENCES `CLIENT`(`ID`) ON DELETE CASCADE
) ENGINE = InnoDB;

CREATE TABLE `SALE_ITEM` (
    `ID` BIGINT NOT NULL AUTO_INCREMENT,
    `STATUS` INT NOT NULL DEFAULT 1,
    `CREATED_BY` VARCHAR(20) DEFAULT 'system',
    `UPDATED_BY` VARCHAR(20) DEFAULT 'system',
    `CREATED_DATE` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `UPDATED_DATE` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    `SALE_ID` BIGINT NOT NULL,
    `PRODUCT_ID` BIGINT NOT NULL,
    `QUANTITY` INT NOT NULL DEFAULT 0,
    `PRODUCT_UNIT_CONVERSION_ID` BIGINT NOT NULL,
    PRIMARY KEY (`ID`),
    CONSTRAINT `FK_SALE_ITEM_PRODUCT` FOREIGN KEY (`PRODUCT_ID`) REFERENCES `PRODUCT`(`ID`) ON DELETE cascade,
    CONSTRAINT `FK_UNIT_CONVERSION_ITEM_PRODUCT` FOREIGN KEY (`PRODUCT_UNIT_CONVERSION_ID`) REFERENCES `PRODUCT_UNIT_CONVERSION`(`ID`) ON DELETE cascade,
    CONSTRAINT `FK_SALE_ITEM_SALE` FOREIGN KEY (`SALE_ID`) REFERENCES `SALE`(`ID`) ON DELETE CASCADE
) ENGINE = InnoDB;
